apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ai.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ai-server
